import { SESSION_USER_DETAILS_KEY } from "./sessionKeys"
import {
  formatMemberUsername,
  isAutoGeneratedPortalUsername,
} from "@/modules/Syndication/usermanagement/memberAdminShared"

function displayNameFromSessionUser(row: Record<string, unknown>): string {
  const first = String(row.firstName ?? row.first_name ?? "").trim()
  const last = String(row.lastName ?? row.last_name ?? "").trim()
  const full = [first, last].filter(Boolean).join(" ")
  if (full) return full
  const email = String(row.email ?? "").trim()
  if (email) return email
  const username = String(row.username ?? "").trim()
  if (username && !isAutoGeneratedPortalUsername(username)) {
    return formatMemberUsername(username)
  }
  return ""
}

/** Display name for the signed-in user (from `userDetails` in sessionStorage). */
export function getSessionUserDisplayName(): string {
  try {
    const raw = sessionStorage.getItem(SESSION_USER_DETAILS_KEY)
    if (!raw) return ""
    const parsed = JSON.parse(raw) as unknown
    if (!Array.isArray(parsed) || parsed.length === 0) return ""
    const entry = parsed[0]
    if (entry == null || typeof entry !== "object" || Array.isArray(entry))
      return ""
    return displayNameFromSessionUser(entry as Record<string, unknown>)
  } catch {
    return ""
  }
}
