import type { FormEvent } from "react"
import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { useLocation } from "react-router-dom"
import { AtSign, Loader2, Mail, Phone, Save, User } from "lucide-react"
import { UsPhoneInput } from "../../common/components/UsPhoneInput"
import {
  national10ToE164,
  nationalDigitsFromStoredPhone,
  nationalTenDigitsFromRawInput,
} from "../../common/phone/usPhoneNumber"
import { toast } from "../../common/components/Toast"
import { focusFirstFormErrorAfterUpdate } from "../../common/utils/scrollToFirstFormError"
import { isAutoGeneratedPortalUsername } from "../Syndication/usermanagement/memberAdminShared"
import { fetchMyProfile, patchMyProfile } from "./accountApi"
import { mergeSessionUserDetails, readSessionUser } from "./sessionUser"

const ACCOUNT_NAME_MIN = 1
const ACCOUNT_NAME_MAX = 100

function str(u: Record<string, unknown>, key: string): string {
  return String(u[key] ?? "").trim()
}

function accountNameForForm(rawUsername: string): string {
  const s = rawUsername.trim()
  if (!s || isAutoGeneratedPortalUsername(s)) return ""
  return s
}

function validateAccountName(value: string): string | null {
  const trimmed = value.trim()
  if (trimmed.length < ACCOUNT_NAME_MIN || trimmed.length > ACCOUNT_NAME_MAX) {
    return `Account name must be between ${ACCOUNT_NAME_MIN} and ${ACCOUNT_NAME_MAX} characters.`
  }
  if (trimmed.toLowerCase().startsWith("invited_")) {
    return "Account name is not available."
  }
  return null
}

export function MyAccountPersonalPage() {
  const personalFormRef = useRef<HTMLFormElement>(null)
  const location = useLocation()
  const [firstName, setFirstName] = useState("")
  const [lastName, setLastName] = useState("")
  const [phoneNationalDigits, setPhoneNationalDigits] = useState("")
  const [email, setEmail] = useState("")
  const [username, setUsername] = useState("")
  const [error, setError] = useState("")
  const [isSaving, setIsSaving] = useState(false)
  const [initialValues, setInitialValues] = useState({
    firstName: "",
    lastName: "",
    phoneNationalDigits: "",
    username: "",
  })

  const loadFromSession = useCallback(() => {
    const u = readSessionUser()
    if (!u) return
    const first = str(u, "firstName")
    const last = str(u, "lastName")
    const phoneNat = nationalDigitsFromStoredPhone(str(u, "phone"))
    const accountName = accountNameForForm(str(u, "username"))
    setFirstName(first)
    setLastName(last)
    setPhoneNationalDigits(phoneNat)
    setUsername(accountName)
    setInitialValues({
      firstName: first,
      lastName: last,
      phoneNationalDigits: phoneNat,
      username: accountName,
    })
    setEmail(str(u, "email"))
  }, [])

  const hasChanges = useMemo(() => {
    const phoneNow = nationalTenDigitsFromRawInput(phoneNationalDigits)
    const phoneInitial = nationalTenDigitsFromRawInput(
      initialValues.phoneNationalDigits,
    )
    return (
      firstName.trim() !== initialValues.firstName ||
      lastName.trim() !== initialValues.lastName ||
      username.trim() !== initialValues.username ||
      phoneNow !== phoneInitial
    )
  }, [
    firstName,
    lastName,
    username,
    phoneNationalDigits,
    initialValues.firstName,
    initialValues.lastName,
    initialValues.username,
    initialValues.phoneNationalDigits,
  ])

  useEffect(() => {
    loadFromSession()
    void fetchMyProfile().then((user) => {
      if (user) mergeSessionUserDetails(user)
      loadFromSession()
    })
  }, [location.pathname, loadFromSession])

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!hasChanges || isSaving) return
    setError("")

    const usernameChanged = username.trim() !== initialValues.username
    if (usernameChanged) {
      const accountNameError = validateAccountName(username)
      if (accountNameError) {
        setError(accountNameError)
        focusFirstFormErrorAfterUpdate({ container: personalFormRef.current })
        return
      }
    }

    const d = nationalTenDigitsFromRawInput(phoneNationalDigits)
    const phoneChanged =
      d !==
      nationalTenDigitsFromRawInput(initialValues.phoneNationalDigits)

    if (phoneChanged) {
      if (d.length > 0 && d.length < 10) {
        setError("Enter a complete 10-digit U.S. phone number.")
        focusFirstFormErrorAfterUpdate({ container: personalFormRef.current })
        return
      }
      if (d.length === 10) {
        const e164 = national10ToE164(phoneNationalDigits)
        if (!e164) {
          setError(
            "Enter a valid U.S. phone number. The area code and next three digits cannot start with 0 or 1, or clear the field.",
          )
          focusFirstFormErrorAfterUpdate({ container: personalFormRef.current })
          return
        }
      }
    }

    setIsSaving(true)
    try {
      const patch: {
        firstName: string
        lastName: string
        phone?: string
        username?: string
      } = { firstName, lastName }
      if (phoneChanged) {
        patch.phone =
          d.length === 0 ? "" : national10ToE164(phoneNationalDigits) ?? ""
      }
      if (usernameChanged) {
        patch.username = username.trim()
      }
      const { user } = await patchMyProfile(patch)
      mergeSessionUserDetails(user)
      loadFromSession()
      toast.success("Personal details saved", "Your details were updated.")
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Could not save personal details.",
      )
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <div className="myaccount_form_body">
      {/* <p className="myaccount_readonly_note">
        Email and account name are managed by your administrator and cannot be
        changed here. Use Save changes to update your first name, last name, and
        phone in your profile (stored on the server).
      </p> */}
      {error ? (
        <p className="um_msg_error" role="alert">
          {error}
        </p>
      ) : null}
      <form ref={personalFormRef} onSubmit={handleSubmit} noValidate>
        <div className="um_field">
          <label htmlFor="myaccount-email" className="um_field_label_row">
            <Mail className="um_field_label_icon" size={17} aria-hidden />
            <span>Email</span>
          </label>
          <input
            id="myaccount-email"
            name="email"
            type="email"
            value={email}
            onChange={() => {}}
            placeholder="name@company.com"
            readOnly
          />
        </div>
        <div className="um_field">
          <label htmlFor="myaccount-username" className="um_field_label_row">
            <AtSign className="um_field_label_icon" size={17} aria-hidden />
            <span>Account name</span>
          </label>
          <input
            id="myaccount-username"
            name="username"
            type="text"
            value={username}
            onChange={(e) => {
              setUsername(e.target.value)
              if (error) setError("")
            }}
            placeholder="Your account name"
            disabled={isSaving}
            autoComplete="username"
            maxLength={ACCOUNT_NAME_MAX}
            aria-invalid={!!error}
          />
        </div>
        <div className="um_field">
          <label htmlFor="myaccount-firstName" className="um_field_label_row">
            <User className="um_field_label_icon" size={17} aria-hidden />
            <span>First name</span>
          </label>
          <input
            id="myaccount-firstName"
            name="firstName"
            type="text"
            value={firstName}
            onChange={(e) => {
              setFirstName(e.target.value)
              if (error) setError("")
            }}
            disabled={isSaving}
            aria-invalid={!!error}
          />
        </div>
        <div className="um_field">
          <label htmlFor="myaccount-lastName" className="um_field_label_row">
            <User className="um_field_label_icon" size={17} aria-hidden />
            <span>Last name</span>
          </label>
          <input
            id="myaccount-lastName"
            name="lastName"
            type="text"
            value={lastName}
            onChange={(e) => {
              setLastName(e.target.value)
              if (error) setError("")
            }}
            disabled={isSaving}
            aria-invalid={!!error}
          />
        </div>
        <div className="um_field">
          <label htmlFor="myaccount-phone" className="um_field_label_row">
            <Phone className="um_field_label_icon" size={17} aria-hidden />
            <span>Phone</span>
          </label>
          <UsPhoneInput
            id="myaccount-phone"
            name="phone"
            nationalDigits={phoneNationalDigits}
            onNationalDigitsChange={(next) => {
              setPhoneNationalDigits(next)
              if (error) setError("")
            }}
            disabled={isSaving}
            className="um_field_input"
            invalidClassName="um_field_input_invalid"
            aria-invalid={!!error}
          />
        </div>
        <div className="myaccount_actions">
          <button
            type="submit"
            className="um_btn_primary"
            disabled={isSaving || !hasChanges}
          >
            {isSaving ? (
              <>
                <Loader2
                  size={16}
                  strokeWidth={2}
                  className="myaccount_btn_spin"
                  aria-hidden
                />
                Saving…
              </>
            ) : (
              <>
                <Save size={16} strokeWidth={2} aria-hidden />
                Save changes
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  )
}
