/** Pending invite placeholder (`invitePendingUser.service`). */
const INVITED_PLACEHOLDER_USERNAME_RE = /^invited_[0-9a-f]+$/i;

/** Self-serve signup when account name is omitted (`deriveSignupUsername`). */
const DERIVED_SIGNUP_USERNAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9_]*_[0-9a-f]{8}$/;

export function isInvitedPlaceholderUsername(
  value: string | null | undefined,
): boolean {
  const s = String(value ?? "").trim();
  return INVITED_PLACEHOLDER_USERNAME_RE.test(s);
}

export function isDerivedSignupUsername(
  value: string | null | undefined,
): boolean {
  const s = String(value ?? "").trim();
  if (!s) return false;
  return DERIVED_SIGNUP_USERNAME_RE.test(s);
}

export function isAutoGeneratedPortalUsername(
  value: string | null | undefined,
): boolean {
  return (
    isInvitedPlaceholderUsername(value) || isDerivedSignupUsername(value)
  );
}

/** Human-facing portal user label (name first; hide internal auto usernames). */
export function formatPortalUserDisplayLabel(u: {
  firstName?: string | null;
  lastName?: string | null;
  username?: string | null;
  companyName?: string | null;
}): string {
  const full = [u.firstName, u.lastName]
    .map((s) => String(s ?? "").trim())
    .filter(Boolean)
    .join(" ");
  if (full) return full;
  const co = String(u.companyName ?? "").trim();
  if (co) return co;
  const un = String(u.username ?? "").trim();
  if (un && !isAutoGeneratedPortalUsername(un)) return un;
  return "—";
}
