import { SESSION_USER_DETAILS_KEY } from "../../../common/auth/sessionKeys";
import {
  getActiveWorkspaceCompanyName,
  getSessionOrganizationCompanyId,
} from "../../../common/auth/sessionOrganization";
import {
  getSessionAccessibleCompanies,
  getSessionPrimaryCompanyName,
} from "../../../common/auth/sessionMemberships";

const ORG_UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function formatValue(value: unknown): string {
  if (value === null || value === undefined) return "—";
  if (typeof value === "object") return JSON.stringify(value);
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return String(value);
}

/** Distinct deals for this member (API: `assignedDealCount` / `assigned_deal_count`). */
export function assignedDealCountFromRow(row: Record<string, unknown>): number {
  const v =
    row.assignedDealCount ??
    row.assigned_deal_count ??
    row.dealCount ??
    row.deal_count;
  if (typeof v === "number" && Number.isFinite(v))
    return Math.max(0, Math.floor(v));
  if (typeof v === "string" && v.trim()) {
    const n = Number(v);
    if (Number.isFinite(n)) return Math.max(0, Math.floor(n));
  }
  return 0;
}

export function accountStatusLabel(row: Record<string, unknown>): string {
  const raw = row.userSignupCompleted ?? row.user_signup_completed;
  const v = String(raw ?? "")
    .trim()
    .toLowerCase();
  if (v === "true") return "Complete";
  if (v === "false") return "Incomplete";
  return formatValue(raw);
}

/** User row status (active = green dot; otherwise coral + label). */
export function userStatusForUi(row: Record<string, unknown>): {
  positive: boolean;
  label: string;
} {
  const raw = String(row.userStatus ?? "").trim();
  if (!raw) return { positive: false, label: "—" };
  const low = raw.toLowerCase();
  if (low === "active") return { positive: true, label: "Active" };
  if (low === "inactive" || low === "suspended") {
    return { positive: false, label: "Inactive" };
  }
  const label = raw
    .split(/[\s_-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
  return { positive: false, label };
}

/** Account signup status (complete = green; invited = blue; expired = coral). */
export function accountStatusForUi(row: Record<string, unknown>): {
  positive: boolean;
  label: string;
  dotTone?: "invited";
} {
  const raw = row.userSignupCompleted ?? row.user_signup_completed;
  const v = String(raw ?? "")
    .trim()
    .toLowerCase();
  if (v === "true") return { positive: true, label: "Complete" };
  if (v === "false") {
    const expRaw = row.inviteExpiresAt ?? row.invite_expires_at;
    if (expRaw) {
      const t = new Date(String(expRaw)).getTime();
      if (!Number.isNaN(t) && Date.now() > t) {
        return { positive: false, label: "Invite expired" };
      }
    }
    return { positive: false, label: "Invited", dotTone: "invited" };
  }
  const l = accountStatusLabel(row);
  if (l === "—") return { positive: false, label: "—" };
  if (l === "Complete") return { positive: true, label: "Complete" };
  if (l === "Incomplete") return { positive: false, label: "Incomplete" };
  return { positive: false, label: l };
}

/** Matches account row label "Invite expired" — pending signup and invite link past expiry. */
export function accountInviteIsExpired(row: Record<string, unknown>): boolean {
  const raw = row.userSignupCompleted ?? row.user_signup_completed;
  const v = String(raw ?? "")
    .trim()
    .toLowerCase();
  if (v !== "false") return false;
  const expRaw = row.inviteExpiresAt ?? row.invite_expires_at;
  if (!expRaw) return false;
  const t = new Date(String(expRaw)).getTime();
  if (Number.isNaN(t)) return false;
  return Date.now() > t;
}

export function companyCellValue(row: Record<string, unknown>): string {
  const raw = row.companyName ?? row.company_name;
  const s = String(raw ?? "").trim();
  return s || "—";
}

/**
 * Backend sets pending-invite usernames to `invited_` + hex (invitePendingUser.service).
 */
const INVITED_PLACEHOLDER_USERNAME_RE = /^invited_[0-9a-f]+$/i;

/** Self-serve signup when account name is omitted (`deriveSignupUsername`). */
const DERIVED_SIGNUP_USERNAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9_]*_[0-9a-f]{8}$/;

export function isInvitedPlaceholderUsername(value: unknown): boolean {
  const s = String(value ?? "").trim();
  return INVITED_PLACEHOLDER_USERNAME_RE.test(s);
}

export function isDerivedSignupUsername(value: unknown): boolean {
  const s = String(value ?? "").trim();
  if (!s) return false;
  return DERIVED_SIGNUP_USERNAME_RE.test(s);
}

export function isAutoGeneratedPortalUsername(value: unknown): boolean {
  return (
    isInvitedPlaceholderUsername(value) || isDerivedSignupUsername(value)
  );
}

/** Username in members UI: em dash when unset or when value is an internal placeholder. */
export function formatMemberUsername(value: unknown): string {
  const s = String(value ?? "")
    .trim()
    .replace(/^@+/, "");
  if (!s || isAutoGeneratedPortalUsername(s)) return "—";
  return s;
}

export function rowDisplayName(row: Record<string, unknown>): string {
  const first = String(row.firstName ?? row.first_name ?? "").trim();
  const last = String(row.lastName ?? row.last_name ?? "").trim();
  return [first, last].filter(Boolean).join(" ") || "—";
}

/** Primary label in members user cells: name when set, otherwise username. */
export function memberUserCellPrimaryLabel(row: Record<string, unknown>): string {
  const name = rowDisplayName(row);
  if (name !== "—") return name;
  return formatMemberUsername(row.username);
}

/**
 * Assignable role codes for platform-admin invites (backend `INVITE_ASSIGNABLE_ROLES`).
 * The Invite member modal filters this list by selected company name (see UserManagementPage).
 */
export const PLATFORM_INVITE_ROLE_OPTIONS: { value: string; label: string }[] = [
  { value: "platform_admin", label: "Platform Admin" },
  { value: "platform_user", label: "Platform user" },
  { value: "company_admin", label: "Company Admin" },
  { value: "company_user", label: "Company Member" },
];

/** Roles a company admin may assign when inviting a member (Invite member modal). */
export const COMPANY_INVITE_ROLE_OPTIONS: { value: string; label: string }[] = [
  { value: "company_admin", label: "Company Admin" },
  { value: "company_user", label: "Company Member" },
];

/** Roles a company admin may assign when editing a member. */
export const COMPANY_EDIT_ROLE_OPTIONS: { value: string; label: string }[] = [
  { value: "company_admin", label: "Company Admin" },
  { value: "company_user", label: "Company Member" },
  // { value: "platform_user", label: "Platform user" },
];

/**
 * Human-readable role name for the members table, modals, export, and search.
 * Aligns with invite/edit options and the Role Definitions panel.
 */
export function memberRoleDisplayName(role: unknown): string {
  const r = String(role ?? "").trim().toLowerCase();
  if (!r) return "—";
  const byCode: Record<string, string> = {
    platform_admin: "Platform Admin",
    platform_user: "Platform user",
    /** Legacy alias stored for some accounts */
    user: "Platform user",
    company_admin: "Company Admin",
    company_user: "Company Member",
    deal_participant: "Deal Participant",
    investor: "Investor",
  };
  if (byCode[r]) return byCode[r];
  const raw = String(role ?? "").trim();
  return (
    raw
      .split(/[\s_-]+/)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
      .join(" ") || "—"
  );
}

function isDealParticipantPortalRole(role: unknown): boolean {
  const r = String(role ?? "").trim().toLowerCase();
  return r === "deal_participant" || r === "deal participant";
}

/** Format a `deal_member` / roster role string for the members table (aligned with backend). */
function formatDealRosterRoleForDisplay(raw: string): string {
  const t = String(raw ?? "").trim();
  if (!t) return "";
  const lower = t.toLowerCase();
  if (
    lower === "lp_investors" ||
    lower === "lp_investor" ||
    lower === "lp investors" ||
    lower === "lp investor"
  ) {
    return "LP Investor";
  }
  if (lower === "deal_participant" || lower === "deal participant") return "";
  return t
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

/** One company–role pair for a portal user (API: `memberships`). */
export interface UserMembership {
  company: string;
  role: string;
}

function membershipPairKey(m: UserMembership): string {
  return `${m.company.trim().toLowerCase()}|${m.role.trim().toLowerCase()}`;
}

export function dedupeMemberships(list: UserMembership[]): UserMembership[] {
  const seen = new Set<string>();
  const out: UserMembership[] = [];
  for (const m of list) {
    const k = membershipPairKey(m);
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(m);
  }
  return out;
}

/**
 * Normalizes `row.memberships` from the API, or falls back to legacy single
 * `companyName` + `role` when absent.
 */
export function parseMembershipsFromRow(
  row: Record<string, unknown>,
): UserMembership[] {
  const raw = row.memberships;
  if (Array.isArray(raw) && raw.length > 0) {
    const out: UserMembership[] = [];
    for (const item of raw) {
      if (item === null || typeof item !== "object" || Array.isArray(item)) {
        continue;
      }
      const rec = item as Record<string, unknown>;
      const company =
        String(
          rec.company ??
            rec.companyName ??
            rec.company_name ??
            rec.organization_name ??
            "",
        ).trim() || "—";
      const role = String(rec.role ?? "").trim() || "—";
      if (role === "—" && company === "—") continue;
      out.push({ company, role });
    }
    if (out.length > 0) return dedupeMemberships(out);
  }
  const company = companyCellValue(row);
  const role = memberRoleDisplayName(row.role);
  if (role === "—") return [];
  return [{ company, role }];
}

export function membershipsSortValue(row: Record<string, unknown>): string {
  return parseMembershipsFromRow(row)
    .map((m) => `${m.company} ${m.role}`)
    .join(" ");
}

/**
 * One role for the Roles column: uses deal roster / LP roles from the API when portal
 * `role` is `deal_participant` (never shows the generic “Deal Participant” label).
 */
export function primaryRoleLabelFromRow(row: Record<string, unknown>): string {
  const rd = String(row.roleDisplay ?? row.role_display ?? "").trim();
  if (rd) return rd;

  const raw = row.role;
  const rawStr = raw != null ? String(raw).trim() : "";

  if (rawStr && isDealParticipantPortalRole(rawStr)) {
    const lp = String(
      row.lp_investor_role_display ?? row.lpInvestorRoleDisplay ?? "",
    ).trim();
    if (lp) return lp;

    const lblRaw = row.dealMemberRoleLabels ?? row.deal_member_role_labels;
    if (Array.isArray(lblRaw) && lblRaw.length > 0) {
      const parts = [
        ...new Set(
          lblRaw
            .map((x) => formatDealRosterRoleForDisplay(String(x ?? "")))
            .filter(Boolean),
        ),
      ];
      if (parts.length > 0) return parts.join(", ");
    }

    const pairs = parseMembershipsFromRow(row);
    const filtered = pairs.filter((p) => {
      const disp = String(p.role ?? "").trim();
      if (!disp || disp === "—") return false;
      return disp.toLowerCase() !== "deal participant";
    });
    if (filtered.length > 0) {
      return [
        ...new Set(filtered.map((p) => String(p.role).trim())),
      ].join(", ");
    }
    return "—";
  }

  if (rawStr !== "") return memberRoleDisplayName(raw);

  const pairs = parseMembershipsFromRow(row);
  if (pairs.length === 0) return "—";
  return pairs[0]!.role;
}

export function roleSortValue(row: Record<string, unknown>): string {
  return primaryRoleLabelFromRow(row);
}

/** Distinct organization names in membership order (Organizations column). */
export function parseOrganizationLabelsFromRow(
  row: Record<string, unknown>,
): string[] {
  const pairs = parseMembershipsFromRow(row);
  const out: string[] = [];
  const seen = new Set<string>();
  for (const p of pairs) {
    const c = p.company.trim();
    if (!c || c === "—") continue;
    const k = c.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(p.company);
  }
  return out;
}

/** Active workspace company when listing members for one organization (Settings → Org Members). */
export type OrganizationDisplayScope = {
  companyId: string;
  companyName?: string;
};

export function resolveOrganizationDisplayScope(
  companyId: string,
  companyNameHint?: string,
): OrganizationDisplayScope | undefined {
  const id = companyId.trim().toLowerCase();
  if (!ORG_UUID_RE.test(id)) return undefined;
  const fromSession = getSessionAccessibleCompanies().find(
    (c) => c.companyId === id,
  )?.companyName;
  const name =
    String(companyNameHint ?? fromSession ?? "").trim() ||
    (getSessionOrganizationCompanyId() === id
      ? getActiveWorkspaceCompanyName().trim()
      : "");
  return { companyId: id, companyName: name || undefined };
}

function scopedCompanyDisplayName(
  row: Record<string, unknown>,
  scope: OrganizationDisplayScope,
): string {
  const hinted = scope.companyName?.trim();
  if (hinted) return hinted;
  const fromRow = companyCellValue(row);
  if (fromRow !== "—") return fromRow;
  const fromSession = getSessionAccessibleCompanies().find(
    (c) => c.companyId === scope.companyId,
  )?.companyName;
  if (fromSession?.trim()) return fromSession.trim();
  return getSessionPrimaryCompanyName().trim() || "Company";
}

/** One organization label when the members list is company-scoped. */
export function organizationLabelsForCompanyScope(
  row: Record<string, unknown>,
  scope?: OrganizationDisplayScope | null,
): string[] {
  if (!scope?.companyId) return parseOrganizationLabelsFromRow(row);
  const name = scopedCompanyDisplayName(row, scope);
  return name ? [name] : [];
}

export function organizationsLabelsPlain(
  row: Record<string, unknown>,
  scope?: OrganizationDisplayScope | null,
): string {
  const list = organizationLabelsForCompanyScope(row, scope);
  if (list.length === 0) return "—";
  return list.join(", ");
}

export function organizationsSortValue(
  row: Record<string, unknown>,
  scope?: OrganizationDisplayScope | null,
): string {
  return organizationLabelsForCompanyScope(row, scope).join(" ");
}

export function formatRoleCsvCell(row: Record<string, unknown>): string {
  return primaryRoleLabelFromRow(row);
}

export function formatOrganizationsCsvCell(
  row: Record<string, unknown>,
  scope?: OrganizationDisplayScope | null,
): string {
  return organizationsLabelsPlain(row, scope);
}

/** Multi-line plain text for view/export previews. */
export function formatMembershipsPlainText(row: Record<string, unknown>): string {
  const pairs = parseMembershipsFromRow(row);
  if (pairs.length === 0) return "—";
  return pairs.map((m) => `${m.company} — ${m.role}`).join("\n");
}

/** Single CSV cell: pairs separated by `; `. */
export function formatMembershipsCsvCell(row: Record<string, unknown>): string {
  return parseMembershipsFromRow(row)
    .map((m) => `${m.company} — ${m.role}`)
    .join("; ");
}

export const MEMBER_STATUS_EDIT_OPTIONS: { value: string; label: string }[] = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
];

export const MEMBER_AUDIT_ACTION_EDIT = "member_edit";
export const MEMBER_AUDIT_ACTION_SUSPEND = "member_suspend";

export function normalizeMemberStatusForEdit(row: Record<string, unknown>): string {
  const s = String(row.userStatus ?? row.user_status ?? "active")
    .trim()
    .toLowerCase();
  if (s === "inactive" || s === "suspended") return "inactive";
  return "active";
}

export function memberRowIsInactive(row: Record<string, unknown>): boolean {
  const s = String(row.userStatus ?? "").trim().toLowerCase();
  return s === "suspended" || s === "inactive";
}

export function memberInvitePending(row: Record<string, unknown>): boolean {
  const v = String(
    row.userSignupCompleted ?? row.user_signup_completed ?? "",
  )
    .trim()
    .toLowerCase();
  return v === "false";
}

/** Compare row id to signed-in user (JWT `id`), case-insensitive. */
export function memberRowIsCurrentUser(
  row: Record<string, unknown>,
  sessionUserId: string,
): boolean {
  if (!sessionUserId) return false;
  const rid = row.id ?? row.userId ?? row.user_id;
  return String(rid ?? "").trim().toLowerCase() === sessionUserId;
}

/**
 * Short label for deal roster / LP shell badges from session `userDetails[0]`.
 * Uses LP investor display from the auth payload when present; otherwise any
 * stored deal-member role string.
 */
export function dealMemberRoleDisplayForShell(
  u: Record<string, unknown>,
): string {
  const lpDisp = String(
    u.lp_investor_role_display ?? u.lpInvestorRoleDisplay ?? "",
  ).trim();
  if (lpDisp) return lpDisp;

  const raw =
    u.deal_member_role_display ??
    u.dealMemberRoleDisplay ??
    u.deal_member_role ??
    u.dealMemberRole ??
    u.your_role ??
    u.yourRole;
  const s = String(raw ?? "").trim();
  if (!s) return "";
  return memberRoleDisplayName(s);
}

export function syncSessionUserDetailsById(
  userId: string,
  patch: Record<string, unknown>,
): void {
  try {
    const raw = sessionStorage.getItem(SESSION_USER_DETAILS_KEY);
    if (!raw) return;
    const arr = JSON.parse(raw) as unknown;
    if (!Array.isArray(arr)) return;
    const next = arr.map((item) => {
      if (
        item !== null &&
        typeof item === "object" &&
        !Array.isArray(item) &&
        String((item as Record<string, unknown>).id) === userId
      ) {
        return { ...(item as Record<string, unknown>), ...patch };
      }
      return item;
    });
    sessionStorage.setItem(SESSION_USER_DETAILS_KEY, JSON.stringify(next));
  } catch {
    /* ignore */
  }
}
