import { FilePenLine } from "lucide-react"
import {
  formatMemberUsername,
  formatValue,
  isAutoGeneratedPortalUsername,
} from "../../../usermanagement/memberAdminShared"
import type { DealInvestorRow } from "../../types/deal-investors.types"
import {
  EMAIL_UNAVAILABLE_LABEL,
  displayEmail,
  isDisplayableEmail,
} from "../../../../../common/utils/displayEmail"

function dealMemberInitials(r: DealInvestorRow): string {
  const u = String(r.userDisplayName ?? "")
    .trim()
    .replace(/^@+/, "")
  if (u.length >= 2 && !isAutoGeneratedPortalUsername(u))
    return u.slice(0, 2).toUpperCase()
  const e = String(r.userEmail ?? "").trim()
  if (isDisplayableEmail(e) && e.length >= 2)
    return e.slice(0, 2).toUpperCase()
  const name = String(r.displayName ?? "").trim()
  const parts = name.split(/\s+/).filter(Boolean)
  if (parts.length >= 2)
    return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase()
  if (name.length >= 2) return name.slice(0, 2).toUpperCase()
  return "?"
}

export function DealMemberUserCell({
  row,
  isDraft,
}: {
  row: DealInvestorRow
  isDraft?: boolean
}) {
  const initials = dealMemberInitials(row)
  const rawEmail = String(row.userEmail ?? "").trim()
  const usernameFormatted = formatMemberUsername(row.userDisplayName)
  const displayFallback = String(formatValue(row.displayName)).trim()
  const nameLine =
    usernameFormatted !== "—"
      ? usernameFormatted
      : displayFallback && displayFallback !== "—"
        ? displayFallback
        : "—"
  const emailText = displayEmail(rawEmail)
  const emailUsable = isDisplayableEmail(rawEmail)

  return (
    <div className="um_user_cell">
      <div className="um_user_avatar_ring" aria-hidden>
        <span className="um_user_initials">{initials}</span>
      </div>
      <div className="um_user_meta">
        <div className="deal_member_user_name_row">
          <span
            className={`um_user_meta_username${
              nameLine === "—" ? " um_user_meta_username--placeholder" : ""
            }`}
          >
            {nameLine}
          </span>
          {isDraft ? (
            <span
              className="deals_list_draft_icon deals_list_draft_icon--draft"
              title="Unsaved draft"
            >
              <FilePenLine size={14} strokeWidth={2} aria-hidden />
              <span className="deals_list_sr_only">Draft</span>
            </span>
          ) : null}
        </div>
        {emailUsable ? (
          <a
            href={`mailto:${encodeURIComponent(rawEmail)}`}
            className="um_user_meta_email um_user_meta_email_link"
          >
            {rawEmail}
          </a>
        ) : (
          <span
            className={`um_user_meta_email${
              emailText === EMAIL_UNAVAILABLE_LABEL ? " um_status_muted" : ""
            }`}
          >
            {emailText}
          </span>
        )}
      </div>
    </div>
  )
}
